name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'dashboard/package-lock.json'

      - name: Create build-fix.js file to handle route groups
        run: |
          cd dashboard
          node -e "
          const fs = require('fs');
          fs.writeFileSync('pre-build-fix.js', \`
          // This is a pre-build step to create empty files
          const fs = require('fs');
          const path = require('path');
          
          console.log('Creating route group directories for static export...');
          
          // Create empty placeholder files for the route groups
          const routeGroupPath = path.join(__dirname, 'src/app/(dashboard)');
          fs.mkdirSync(path.join(routeGroupPath, '_static'), { recursive: true });
          fs.writeFileSync(path.join(routeGroupPath, '_static/placeholder.js'), 'export default {};');
          
          // Additional exports compatibility fixes
          const appDir = path.join(__dirname, 'src/app');
          fs.mkdirSync(path.join(appDir, '_static'), { recursive: true });
          fs.writeFileSync(path.join(appDir, '_static/placeholder.js'), 'export default {};');
          
          console.log('Pre-build fixes applied successfully!');
          \`);
          "

      - name: Install dependencies
        run: |
          cd dashboard
          npm install --legacy-peer-deps

      - name: Run pre-build fixes
        run: |
          cd dashboard
          node pre-build-fix.js

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build Next.js app
        run: |
          cd dashboard
          npm run build
        env:
          GITHUB_ACTIONS: true

      - name: Fix paths and create nojekyll file
        run: |
          cd dashboard/out
          # Create a .nojekyll file to bypass Jekyll processing
          touch .nojekyll
          
          # Create 404.html for better GitHub Pages navigation
          cp index.html 404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dashboard/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 